version: '3.8'

services:
  db:
    image: postgres:15
    container_name: birthday_reminder_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: birthday_reminder
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
